version: "2.2"
services:
  inventory:
    image: inventory
    build:
      context: inventory-svc
    networks:
      - service_mesh
    ports:
      - 8080:8080
  shoping:
    image: shopping
    build:
      context: shopping-svc
    networks:
      - service_mesh
    environment:
      - INVENTORY_SVC_BASEURL=http://inventory:8080
    ports:
      - 8090:8090
networks:
  service_mesh:


