swagger: "2.0"
info:
  title: shopping-service-api-spec
  version: "1.0.0"
tags:
- name: "item"
  description: "Endpoints for manipulating items"
paths:
  /items:
    get:
      tags:
        - "item"
      operationId: getAllitems
      summary: Retrieves all items
      produces:
      - application/json
      responses:
        "200":
          description: |-
            200 response
          examples:
            application/json: |-
              [
                {
                  "name": "item1",
                  "price": 1.11,
                  "inventoryId": 123,
                  "id": 1
                },
                {
                  "name": "item2",
                  "price": 2.22,
                  "inventoryId": 321,
                  "id": 2
                }
              ]

    post:
      tags:
      - "item"
      operationId: additem
      summary: Adds a new item
      consumes:
        - application/json
      parameters:
        - in: body
          name: item
          schema:
            type: object
            required:
              - name
              - price
              - inventoryId
            properties:
              name:
                type: string
              price:
                type: number
              inventoryId:
                type: integer

      produces:
        - application/json
      responses:
        201:
          description: Created User Object
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Item Id
              inventoryId:
                type: integer
                description: Item Inventory Id
              name:
                type: string
                description: Item name
              price:
                type: number
                description: Item price

host: 35.234.149.119/shopping
schemes:
- http
consumes:
- application/json
